/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.uts;

import java.util.HashSet;

/**
 *
 * @author ASUS
 */
public class pertanyaan1 extends javax.swing.JFrame {

    /**
     * Creates new form pertanyaan1
     */
    public pertanyaan1() {
        this.setExtendedState(Login.MAXIMIZED_BOTH);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DaftarPertanyaan = new javax.swing.JTabbedPane();
        Pertanyaan1 = new javax.swing.JPanel();
        c = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        d = new javax.swing.JButton();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        Pertanyaan2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        a1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        e1 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        g1 = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        ok1 = new javax.swing.JButton();
        Pertanyaan3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        a2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        d2 = new javax.swing.JButton();
        e2 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        g2 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();
        ok2 = new javax.swing.JButton();
        Pertanyaan4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        a3 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        d3 = new javax.swing.JButton();
        ok3 = new javax.swing.JButton();
        e3 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        g3 = new javax.swing.JTextField();
        h3 = new javax.swing.JTextField();
        Pertanyaan5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        a4 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        d4 = new javax.swing.JButton();
        ok4 = new javax.swing.JButton();
        e4 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        g4 = new javax.swing.JTextField();
        h4 = new javax.swing.JTextField();
        Skor = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        ok5 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        Closing = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        tutup = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(28, 5, 34));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 440, 60));

        Pertanyaan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c.setText("c. Saya bisa langsung berinteraksi");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        Pertanyaan1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 152, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setText("Apakah kamu suka bersosialisasi");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Pertanyaan1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 407, -1));

        a.setText("a. Saya selalu menghindar");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        Pertanyaan1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 76, -1, -1));

        b.setText("b. Saya senang sendiri");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        Pertanyaan1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 114, -1, -1));

        d.setText("d. ya jika dengan orang yang saya kenal");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        Pertanyaan1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 190, -1, -1));

        e.setEditable(false);
        Pertanyaan1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 228, 59, -1));

        f.setEditable(false);
        Pertanyaan1.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 263, 59, -1));

        g.setEditable(false);
        Pertanyaan1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 228, 61, -1));

        h.setEditable(false);
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        Pertanyaan1.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 61, -1));

        ok.setText("ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        Pertanyaan1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        DaftarPertanyaan.addTab("tab1", Pertanyaan1);

        Pertanyaan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setText("Bla Bla");
        Pertanyaan2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 34, -1, -1));

        a1.setText("a.");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        Pertanyaan2.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 78, -1, -1));

        b1.setText("b.");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        Pertanyaan2.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 116, -1, -1));

        c1.setText("c.");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        Pertanyaan2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 161, -1, -1));

        d1.setText("d.");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        Pertanyaan2.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 199, -1, -1));
        Pertanyaan2.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 237, 47, -1));
        Pertanyaan2.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 279, 47, -1));
        Pertanyaan2.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 237, 45, -1));
        Pertanyaan2.add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 279, 45, -1));

        ok1.setText("Ok");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });
        Pertanyaan2.add(ok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 278, -1, -1));

        DaftarPertanyaan.addTab("tab2", Pertanyaan2);

        jTextField3.setText("Bla Bla");

        a2.setText("a.");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        b2.setText("b.");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        c2.setText("c.");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        d2.setText("d.");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });

        ok2.setText("Ok");
        ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pertanyaan3Layout = new javax.swing.GroupLayout(Pertanyaan3);
        Pertanyaan3.setLayout(Pertanyaan3Layout);
        Pertanyaan3Layout.setHorizontalGroup(
            Pertanyaan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pertanyaan3Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(Pertanyaan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2)
                    .addComponent(c2)
                    .addComponent(d2)
                    .addGroup(Pertanyaan3Layout.createSequentialGroup()
                        .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pertanyaan3Layout.createSequentialGroup()
                        .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(ok2))
                    .addGroup(Pertanyaan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Pertanyaan3Layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(a2)))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        Pertanyaan3Layout.setVerticalGroup(
            Pertanyaan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pertanyaan3Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a2)
                .addGap(9, 9, 9)
                .addComponent(b2)
                .addGap(16, 16, 16)
                .addComponent(c2)
                .addGap(9, 9, 9)
                .addComponent(d2)
                .addGap(9, 9, 9)
                .addGroup(Pertanyaan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(e2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(Pertanyaan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok2)
                    .addGroup(Pertanyaan3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(Pertanyaan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        DaftarPertanyaan.addTab("tab3", Pertanyaan3);

        jTextField4.setText("bla bla");

        a3.setText("a.");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        b3.setText("b.");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        c3.setText("c.");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        d3.setText("d.");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });

        ok3.setText("Ok");
        ok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pertanyaan4Layout = new javax.swing.GroupLayout(Pertanyaan4);
        Pertanyaan4.setLayout(Pertanyaan4Layout);
        Pertanyaan4Layout.setHorizontalGroup(
            Pertanyaan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pertanyaan4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ok3))
            .addGroup(Pertanyaan4Layout.createSequentialGroup()
                .addGroup(Pertanyaan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pertanyaan4Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pertanyaan4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(a3))
                    .addGroup(Pertanyaan4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b3))
                    .addGroup(Pertanyaan4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(c3))
                    .addGroup(Pertanyaan4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pertanyaan4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pertanyaan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(e3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        Pertanyaan4Layout.setVerticalGroup(
            Pertanyaan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pertanyaan4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pertanyaan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pertanyaan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok3))
        );

        DaftarPertanyaan.addTab("tab4", Pertanyaan4);

        jTextField5.setText("bla bla");

        a4.setText("a.");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });

        b4.setText("b.");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        c4.setText("c.");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        d4.setText("d.");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });

        ok4.setText("Ok");
        ok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pertanyaan5Layout = new javax.swing.GroupLayout(Pertanyaan5);
        Pertanyaan5.setLayout(Pertanyaan5Layout);
        Pertanyaan5Layout.setHorizontalGroup(
            Pertanyaan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pertanyaan5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ok4))
            .addGroup(Pertanyaan5Layout.createSequentialGroup()
                .addGroup(Pertanyaan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pertanyaan5Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pertanyaan5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(a4))
                    .addGroup(Pertanyaan5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b4))
                    .addGroup(Pertanyaan5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(c4))
                    .addGroup(Pertanyaan5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pertanyaan5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pertanyaan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(e4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(d4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        Pertanyaan5Layout.setVerticalGroup(
            Pertanyaan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pertanyaan5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pertanyaan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pertanyaan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok4))
        );

        DaftarPertanyaan.addTab("tab4", Pertanyaan5);

        jTextField6.setText("jTextField1");

        jTextField7.setText("jTextField2");

        jTextField8.setText("jTextField3");

        jTextField9.setText("jTextField4");

        ok5.setText("Ok");
        ok5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok5ActionPerformed(evt);
            }
        });

        jTextField10.setText("jTextField5");

        jTextField11.setText("jTextField6");

        jTextField12.setText("jTextField7");

        jTextField13.setText("jTextField8");

        javax.swing.GroupLayout SkorLayout = new javax.swing.GroupLayout(Skor);
        Skor.setLayout(SkorLayout);
        SkorLayout.setHorizontalGroup(
            SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SkorLayout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(SkorLayout.createSequentialGroup()
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SkorLayout.createSequentialGroup()
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SkorLayout.createSequentialGroup()
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SkorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok5)
                .addContainerGap())
        );
        SkorLayout.setVerticalGroup(
            SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SkorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SkorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(ok5)
                .addGap(31, 31, 31))
        );

        DaftarPertanyaan.addTab("tab4", Skor);

        jTextField14.setText("Motivasi");

        jTextField15.setText("jTextField2");

        tutup.setText("Tutup");
        tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClosingLayout = new javax.swing.GroupLayout(Closing);
        Closing.setLayout(ClosingLayout);
        ClosingLayout.setHorizontalGroup(
            ClosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClosingLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(ClosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ClosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tutup)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        ClosingLayout.setVerticalGroup(
            ClosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClosingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(tutup)
                .addContainerGap())
        );

        DaftarPertanyaan.addTab("tab7", Closing);

        getContentPane().add(DaftarPertanyaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 442, 357));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//pilihan abcd segaja dibuat button untuk menampilkan hasil nilai setelah memilih secara otomatis.
    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
       e.setText("a.20");
       f.setText("b.30");
       g.setText("b.40");
       h.setText("b.50");
    
        
    }//GEN-LAST:event_dActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
       e.setText("a.20");
       f.setText("b.30");
       g.setText("b.40");
       h.setText("b.50");
   
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
       e.setText("a.20");
       f.setText("b.30");
       g.setText("b.40");
       h.setText("b.50");
   
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
       e.setText("a.20");
       f.setText("b.30");
       g.setText("b.40");
       h.setText("b.50");
   
    }//GEN-LAST:event_cActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if(e.getText().equals("a.20")){
        DaftarPertanyaan.setSelectedIndex(1);
        }
    }//GEN-LAST:event_okActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        e1.setText("a.20");
        f1.setText("b.30");
        g1.setText("b.40");
        h1.setText("b.50");
    }//GEN-LAST:event_a1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        e1.setText("a.20");
        f1.setText("b.30");
        g1.setText("b.40");
        h1.setText("b.50");
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        e1.setText("a.20");
        f1.setText("b.30");
        g1.setText("b.40");
        h1.setText("b.50");
    }//GEN-LAST:event_c1ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        e1.setText("a.20");
        f1.setText("b.30");
        g1.setText("b.40");
        h1.setText("b.50");
    }//GEN-LAST:event_d1ActionPerformed

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        if(e.getText().equals("a.20")){
        DaftarPertanyaan.setSelectedIndex(2);
        }
    }//GEN-LAST:event_ok1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        e2.setText("a.20");
        f2.setText("b.30");
        g2.setText("b.40");
        h2.setText("b.50");
    }//GEN-LAST:event_a2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        e2.setText("a.20");
        f2.setText("b.30");
        g2.setText("b.40");
        h2.setText("b.50");
    }//GEN-LAST:event_b2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        e2.setText("a.20");
        f2.setText("b.30");
        g2.setText("b.40");
        h2.setText("b.50");
    }//GEN-LAST:event_c2ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        e2.setText("a.20");
        f2.setText("b.30");
        g2.setText("b.40");
        h2.setText("b.50");
    }//GEN-LAST:event_d2ActionPerformed

    private void ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok2ActionPerformed
        if(e.getText().equals("a.20")){
        DaftarPertanyaan.setSelectedIndex(3);
    }//GEN-LAST:event_ok2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        e3.setText("a.20");
        f3.setText("b.30");
        g3.setText("b.40");
        h3.setText("b.50");
    }//GEN-LAST:event_a3ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        e3.setText("a.20");
        f3.setText("b.30");
        g3.setText("b.40");
        h3.setText("b.50");
    }//GEN-LAST:event_b3ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        e3.setText("a.20");
        f3.setText("b.30");
        g3.setText("b.40");
        h3.setText("b.50");
    }//GEN-LAST:event_c3ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        e3.setText("a.20");
        f3.setText("b.30");
        g3.setText("b.40");
        h3.setText("b.50");
    }//GEN-LAST:event_d3ActionPerformed

    private void ok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok3ActionPerformed
        if(e3.getText().equals("a.20")){
        DaftarPertanyaan.setSelectedIndex(4);
        }
    }//GEN-LAST:event_ok3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        e4.setText("a.20");
        f4.setText("b.30");
        g4.setText("b.40");
        h4.setText("b.50");
    }//GEN-LAST:event_a4ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        e4.setText("a.20");
        f4.setText("b.30");
        g4.setText("b.40");
        h4.setText("b.50");
    }//GEN-LAST:event_b4ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        e4.setText("a.20");
        f4.setText("b.30");
        g4.setText("b.40");
        h4.setText("b.50");
    }//GEN-LAST:event_c4ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        e4.setText("a.20");
        f4.setText("b.30");
        g4.setText("b.40");
        h4.setText("b.50");
    }//GEN-LAST:event_d4ActionPerformed

    private void ok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok4ActionPerformed
         if(e3.getText().equals("a.20")){
        DaftarPertanyaan.setSelectedIndex(5);
            
        }
        
    }//GEN-LAST:event_ok4ActionPerformed

    private void ok5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok5ActionPerformed

        DaftarPertanyaan.setSelectedIndex(6);
    }//GEN-LAST:event_ok5ActionPerformed

    private void tutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupActionPerformed
        Splash sp =new Splash();
        sp.setVisible(true);
    }//GEN-LAST:event_tutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pertanyaan1().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Closing;
    private javax.swing.JTabbedPane DaftarPertanyaan;
    private javax.swing.JPanel Pertanyaan1;
    private javax.swing.JPanel Pertanyaan2;
    private javax.swing.JPanel Pertanyaan3;
    private javax.swing.JPanel Pertanyaan4;
    private javax.swing.JPanel Pertanyaan5;
    private javax.swing.JPanel Skor;
    private javax.swing.JButton a;
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton b;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton c;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton d;
    private javax.swing.JButton d1;
    private javax.swing.JButton d2;
    private javax.swing.JButton d3;
    private javax.swing.JButton d4;
    private javax.swing.JTextField e;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField f;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField g;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField g4;
    private javax.swing.JTextField h;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JTextField h4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok1;
    private javax.swing.JButton ok2;
    private javax.swing.JButton ok3;
    private javax.swing.JButton ok4;
    private javax.swing.JButton ok5;
    private javax.swing.JButton tutup;
    // End of variables declaration//GEN-END:variables
}
