/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Awal extends javax.swing.JFrame {

    /**
     * Creates new form Awal
     */
    public Awal() {
        this.setUndecorated(true);
        initComponents();
        initLevel0();        
    }
    private void initLevel0(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tombollogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tombolberanda = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tombolcs = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JTabbedPane();
        branda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Keluar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(454, 647));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(11, 26, 130));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(11, 26, 130));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombollogin.setBackground(new java.awt.Color(0, 0, 102));
        tombollogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolloginMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login");

        javax.swing.GroupLayout tombolloginLayout = new javax.swing.GroupLayout(tombollogin);
        tombollogin.setLayout(tombolloginLayout);
        tombolloginLayout.setHorizontalGroup(
            tombolloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        tombolloginLayout.setVerticalGroup(
            tombolloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tombolloginLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jPanel4.add(tombollogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 30));

        tombolberanda.setBackground(new java.awt.Color(0, 0, 102));
        tombolberanda.setForeground(new java.awt.Color(255, 255, 255));
        tombolberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolberandaMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Beranda");

        javax.swing.GroupLayout tombolberandaLayout = new javax.swing.GroupLayout(tombolberanda);
        tombolberanda.setLayout(tombolberandaLayout);
        tombolberandaLayout.setHorizontalGroup(
            tombolberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolberandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tombolberandaLayout.setVerticalGroup(
            tombolberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tombolberandaLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jPanel4.add(tombolberanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 110, 30));

        tombolcs.setBackground(new java.awt.Color(0, 0, 102));
        tombolcs.setForeground(new java.awt.Color(0, 0, 102));
        tombolcs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolcsMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact Person");

        javax.swing.GroupLayout tombolcsLayout = new javax.swing.GroupLayout(tombolcs);
        tombolcs.setLayout(tombolcsLayout);
        tombolcsLayout.setHorizontalGroup(
            tombolcsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolcsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tombolcsLayout.setVerticalGroup(
            tombolcsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tombolcsLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel4.add(tombolcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/beranda atas.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        panel.setBackground(new java.awt.Color(11, 26, 130));

        branda.setBackground(new java.awt.Color(11, 26, 130));
        branda.setLayout(null);

        jLabel2.setFont(new java.awt.Font("STXinwei", 1, 21)); // NOI18N
        jLabel2.setText("Online Mental Heart Supporting Group");
        branda.add(jLabel2);
        jLabel2.setBounds(20, 50, 610, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Selamat datang di Aplikasi Online Mental Health Supporting Group.\nDengan pandemi covid 19 ini, kehidupan manusia menggalami perubahan yang signifikan.\nPeruabahan rutinitas semua faktor harus disesuaikan termasuk kesehatan,pekerjaan maupun perekonomian.\n\nDengan adanya media sosial isu isu mengenai dunia luar semakin berkembang dengan bebas nya\ntanpa ada filter. Sehingga membuat keadaan mental dan fisik terganggu dalam waktu bersaaman.\n\nKami harap dengan adanya aplikasi ini anda akan merasa terbanttu dalam menggatasi permasalahan yang anda alamai,\ndengan cara menghitung seberapa berat depresi rasa panik yang anda alami.\n\nAplikasi ini tidak menjamin 100% keakuratan.");
        jScrollPane3.setViewportView(jTextArea2);

        branda.add(jScrollPane3);
        jScrollPane3.setBounds(20, 90, 410, 350);

        Keluar.setBackground(new java.awt.Color(255, 255, 255));
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        branda.add(Keluar);
        Keluar.setBounds(340, 540, 90, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/Beranda Utamaa.png"))); // NOI18N
        branda.add(jLabel3);
        jLabel3.setBounds(-30, -70, 549, 735);

        panel.addTab("tab3", branda);

        jPanel2.setBackground(new java.awt.Color(11, 26, 130));
        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/Beranda Utamaa.png"))); // NOI18N
        jLabel4.setText("jLabel3");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 604, 735);

        panel.addTab("tab1", jPanel2);

        jPanel5.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 650));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolloginMousePressed
        setColour(tombollogin);
        ResetColour(new JPanel []{tombolcs, tombolberanda});
        Login log=new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolloginMousePressed

    private void tombolberandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolberandaMousePressed
        setColour(tombolberanda);
        //ResetColour(new JPanel[]{tombollogin, tombolcs});
        panel.setSelectedIndex(0);
    }//GEN-LAST:event_tombolberandaMousePressed

    private void tombolcsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolcsMousePressed
        setColour(tombolcs);
        ResetColour(new JPanel[]{tombolberanda, tombollogin});
        Cs cs=new Cs();
        cs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolcsMousePressed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        int dialogButton = JOptionPane.showConfirmDialog (null, "Apakah anda yakin ingin keluar", "PERINGATAN", JOptionPane. YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(dialogButton == JOptionPane.YES_OPTION){
                System.exit(0);
            }
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Awal().setVisible(true);
            }
        });
    }
    private void setColour(JPanel pane){
        pane.setBackground(new Color(255, 255, 0));
    }
    private void ResetColour(JPanel[] pane){
        for(int i=0; i<pane.length; i++){
            pane[i].setBackground(new Color(255, 255, 255));
        }
    }
   
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Keluar;
    private javax.swing.JPanel branda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel tombolberanda;
    private javax.swing.JPanel tombolcs;
    private javax.swing.JPanel tombollogin;
    // End of variables declaration//GEN-END:variables
}
