/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar;

import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Penutup extends javax.swing.JFrame {

    /**
     * Creates new form Penutup
     */
    public Penutup() {
        this.setUndecorated(true);
        initComponents();
        initLevel0();
    }
    private void initLevel0(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        skorcemas = new javax.swing.JTextField();
        skordepresi = new javax.swing.JTextField();
        skortotal = new javax.swing.JTextField();
        Namaakhir = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Predikat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        skorcemas.setEditable(false);
        skorcemas.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(skorcemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, -1));

        skordepresi.setEditable(false);
        skordepresi.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(skordepresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 90, -1));

        skortotal.setEditable(false);
        skortotal.setBackground(new java.awt.Color(204, 204, 255));
        skortotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skortotalActionPerformed(evt);
            }
        });
        jPanel1.add(skortotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 102, 90, 30));

        Namaakhir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Namaakhir.setForeground(new java.awt.Color(255, 204, 204));
        Namaakhir.setText("trt");
        jPanel1.add(Namaakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 240, 60));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 204));
        jLabel7.setText("Cemas :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Depresi :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        jLabel5.setFont(new java.awt.Font("STXinwei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SKOR ANDA :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 30));

        Predikat.setFont(new java.awt.Font("Wide Latin", 0, 8)); // NOI18N
        Predikat.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Predikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 390, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/emot sedih.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("HALLO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/Penutup.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void skortotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skortotalActionPerformed
  
        
    }//GEN-LAST:event_skortotalActionPerformed

    
    /**
     * @param args the command line arguments
     */
 

    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penutup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penutup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penutup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penutup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penutup().setVisible(true);
            }
        });
        
    }
    void update(String str){
        Namaakhir.setText(str);
    }
    void update1(String tes, String tes1, String tes2){
        skortotal.setText(tes);
        skordepresi.setText(tes1);
        skorcemas.setText(tes2);
    }
    void update2(String str){
        Predikat.setText(str);
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Namaakhir;
    private javax.swing.JLabel Predikat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField skorcemas;
    private javax.swing.JTextField skordepresi;
    private javax.swing.JTextField skortotal;
    // End of variables declaration//GEN-END:variables
}
